name: Build & Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Make mvnw executable
        working-directory: ./gait-analysis-backend
        run: chmod +x ./mvnw

      - name: Unit Tests
        working-directory: ./gait-analysis-backend
        env:
          MQTT_CLIENT_ENDPOINT: ${{ secrets.MQTT_CLIENT_ENDPOINT }}
          MQTT_CLIENT_ID: ${{ secrets.MQTT_CLIENT_ID }}
          MQTT_AWS_ACCESS_KEY: ${{ secrets.MQTT_AWS_ACCESS_KEY }}
          MQTT_AWS_ACCESS_ID: ${{ secrets.MQTT_AWS_ACCESS_ID }}
        run: ./mvnw -B test --file pom.xml

      - name: Build the application
        working-directory: ./gait-analysis-backend
        run: |
          ./mvnw clean
          ./mvnw -B package --file pom.xml